### ISSUE TITLE
Failure to compile with make

### ISSUE THREAD

**Issue by tyyan** [kevinlb1/CATS#1] opened 2019-07-08 23:30 UTC
I'm having trouble compiling the code on linux.
I am trying to compile with LPSolve and modified the Makefile accordingly.

Below is the error message:

g++  -O5 -DNDEBUG -DLINUX -Ilp_solve_4.0  -c -o regions.o ../regions.cpp
../regions.cpp: In member function ‘bool Regions::IsConnectedLocations(int, int)’:
../regions.cpp:30:31: error: qualified-id in declaration before ‘(’ token
 void Regions::ConnectLocations(int loc1, int loc2)
                               ^
../regions.cpp:40:22: error: qualified-id in declaration before ‘(’ token
 void Regions::Connect(int i, int j, int x, int y)
                      ^
../regions.cpp:50:26: error: qualified-id in declaration before ‘(’ token
 bool Regions::IsConnected(int i, int j, int x, int y)
                          ^
../regions.cpp:66:22: error: qualified-id in declaration before ‘(’ token
 int Regions::BuildMap()
                      ^
../regions.cpp:110:25: error: qualified-id in declaration before ‘(’ token
 void Regions::DisplayMap(char * edgefile, char * cityfile)
                         ^
../regions.cpp:148:22: error: qualified-id in declaration before ‘(’ token
 double Regions::Value(bid_type_for_generating &b)
                      ^
../regions.cpp:162:28: error: qualified-id in declaration before ‘(’ token
 double Regions::CommonValue(bid_type_for_generating &b)
                            ^
../regions.cpp:174:26: error: qualified-id in declaration before ‘(’ token
 int Regions::InBidAlready(bid_type_for_generating &b, int new_item)
                          ^
../regions.cpp:188:36: error: qualified-id in declaration before ‘(’ token
 double Regions::weightFromLocations(int a, int b)
                                    ^
../regions.cpp:198:33: error: qualified-id in declaration before ‘(’ token
 void Regions::Add_Good_to_Bundle(bid_type_for_generating * b)
                                 ^
../regions.cpp:272:25: error: qualified-id in declaration before ‘(’ token
 int Regions::bid_compare(const void * a, const void * b)
                         ^
../regions.cpp:287:42: error: qualified-id in declaration before ‘(’ token
 Bid *Regions::MakeGeneratedBidIntoRealBid(bid_type_for_generating *b)
                                          ^
../regions.cpp:287:67: error: expected primary-expression before ‘*’ token
 Bid *Regions::MakeGeneratedBidIntoRealBid(bid_type_for_generating *b)
                                                                   ^
../regions.cpp:287:68: error: ‘b’ was not declared in this scope
 Bid *Regions::MakeGeneratedBidIntoRealBid(bid_type_for_generating *b)
                                                                    ^
../regions.cpp:298:23: error: qualified-id in declaration before ‘(’ token
 int Regions::Identical(bid_type_for_generating &a, bid_type_for_generating &b)
                       ^
../regions.cpp:324:26: error: qualified-id in declaration before ‘(’ token
 BidSet *Regions::generate(Param &p)
                          ^
../regions.cpp:324:33: error: expected primary-expression before ‘&’ token
 BidSet *Regions::generate(Param &p)
                                 ^
../regions.cpp:324:34: error: ‘p’ was not declared in this scope
 BidSet *Regions::generate(Param &p)
                                  ^
../regions.cpp:540:20: error: qualified-id in declaration before ‘(’ token
 void Regions::usage(bool arbitrary)
                    ^
../regions.cpp:570:24: error: expected primary-expression before ‘&’ token
 Regions::Regions(Param &p, char * argv[], int argc)
                        ^
../regions.cpp:570:28: error: expected primary-expression before ‘char’
 Regions::Regions(Param &p, char * argv[], int argc)
                            ^~~~
../regions.cpp:570:43: error: expected primary-expression before ‘int’
 Regions::Regions(Param &p, char * argv[], int argc)
                                           ^~~
../regions.cpp:570:51: error: cannot call constructor ‘Regions::Regions’ directly [-fpermissive]
 Regions::Regions(Param &p, char * argv[], int argc)
                                                   ^
../regions.cpp:570:51: note: for a function-style cast, remove the redundant ‘::Regions’
../regions.cpp:769:19: error: no matching function for call to ‘Regions::Regions()’
 Regions::~Regions()
                   ^
In file included from ../regions.cpp:13:0:
../regions.h:20:13: note: candidate: virtual Regions::~Regions()
     virtual ~Regions();
             ^
../regions.h:20:13: note:   candidate expects 1 argument, 0 provided
../regions.cpp:780:30: error: qualified-id in declaration before ‘(’ token
 char *Regions::outputSettings(bool tofile)
                              ^
../regions.cpp:780:31: error: expected primary-expression before ‘bool’
 char *Regions::outputSettings(bool tofile)
                               ^~~~
../regions.cpp:845:30: error: qualified-id in declaration before ‘(’ token
 void Regions::randomizeParams(Param &p)
                              ^
../regions.cpp:921:1: error: expected ‘}’ at end of input
 }
 ^
<builtin>: recipe for target 'regions.o' failed
make[1]: *** [regions.o] Error 1

**Comment by lythronaxargestes** [comment] 2019-07-12 22:42
Missing bracket fixed in 1b0a74db0c844403136ab1013f0f96373206c4c2. Keeping the issue open for now until confirmed as solved.

**Comment by tyyan** [comment] 2019-07-13 02:55
Now it is crashing here:

gcc -o demo -O3 -Wall -pedantic -ansi demo.o liblpk.a -lfl -lm
/usr/bin/ld: cannot find -lfl
collect2: error: ld returned 1 exit status
Makefile:67: recipe for target 'demo' failed
make[1]: *** [demo] Error 1

How to obtain this lfl for lp_solve_4.0

**Comment by lythronaxargestes** [comment] 2019-07-13 03:33
Could you try installing `flex`?
`sudo apt-get install flex`

**Comment by tyyan** [comment] 2019-07-13 03:41
I have flex:

~/CATS$ which flex
/usr/bin/flex

**Comment by lythronaxargestes** [comment] 2019-07-13 04:02
In that case, could you try to locate a `libfl.so` (or `libfl.so.*`, if there's a version associated with the shared object file) in `/usr/lib`, `/usr/lib64`, or similar? It should be present, since it is a dependency of `flex`.

**Comment by tyyan** [comment] 2019-07-13 23:41
Thanks! It compiled.

Puzzlingly, it's unclear to me why executing the file doesn't work:

~/CATS$ ./cats -d arbitrary -goods 9 -bids 10
Error: unknown parameter 9

**Comment by lythronaxargestes** [comment] 2019-07-13 23:45
Great to hear! I feel like this is a separate bug, so I'll close this issue and open another.

**Closed as completed by lythronaxargestes** 2019-07-13 23:45 UTC
Labels: bug
